# create_flmd_dd.R #############################################################

# Objective: 
  # Create an FLMD with the cols: File_Name, File_Description, Standard, Header_Rows, Column_or_Row_Name_Position, File_Path
  # Create a DD with the cols: Column_or_Row_Name, Unit, Definition, Data_Type, Term_Type, Missing_Value_Code

# Directions: 
  # 1. Fill out user inputs; then run the chunk. 
  # 2. Run the following chunks (you do not need to edit the code): Prep Script, Get Files, Create FLMD, Create DD
  # 3. Optionally, add code into the "Data Package Specific Edits" section if needed
  # 4. Run the "Export" chunk (you do not need to edit the code)

# If you need to edit the functions `get_files()`, `create_flmd()`, or
# `create_dd()`, refer to test-create_flmd() and test-create_dd() to ensure that
# your updates work as expected and haven't broken any existing functionality.

rm(list=ls(all=T))

### USER INPUTS ################################################################

#### REQUIRED ----

# directory = string of the absolute folder file path; do not include "/" at end.
my_directory = 'Z:/00_ESSDIVE/01_Study_DPs/PRT_Data_Package/PRT_Data_Package'

# dp_keyword = string of the data package name; this will be used to name the placeholder flmd, dd, readme files in the flmd and name the FLMD and DD files. Optional argument; default is "data_package".
my_dp_keyword = "PRT"

# out_dir = string of the absolute folder you want the flmd and dd saved to; do not include "/" at end.
my_out_dir = my_directory

# populate_dd_flmd = indicate if you would like query the database to populate the dd and flmd. T/F
  populate_dd_flmd = T

#### OPTIONAL ----

# TIPS for including/excluding files: 
# Example 1: Suppose your data package contains 100 sensor files with
# standardized "Goldman" headers and 5 regular CSV files. Instead of writing
# out all 100 file names just to exclude them, you can use the include_files
# argument to explicitly list the 5 files you do want to process. This is more
# efficient and makes your code easier to manage.

# Example 2: If you have 75 regular files and 3 files with header rows, you
# can process them separately by first running the function with
# query_header_info = TRUE and include_files set to the 3 files to extract
# their header metadata. Then, run the function again with query_header_info =
# FALSE and exclude_files set to the same 3 files to process the 75 regular
# files. Finally, bind the outputs from both runs to combine them into a
# single FLMD.

# exclude_files = vector of files (relative file path + file name; no / at beginning of path) to exclude from within the dir. Optional argument; default is NA_character_. (Tip: Select files in file browser. Click "Copy Path". Paste within c() here. To add commas: Shift+Alt > drag to select all lines > end > comma) 
user_exclude_files =  c("PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-11-19_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-11-19_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-11-19_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01_2025-01-22_EnvContext-2.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01_2025-01-22_EnvContext-3.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01_2025-10-15_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01_2025-10-15_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01_2025-10-15_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01A_2025-08-06_EnvContext-1.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01A_2025-10-15_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM01A_2025-10-15_EnvContext-2.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2024-11-17_EnvContext-6.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-03-19_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-03-19_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-03-19_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-05-06_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-05-06_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-05-06_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-05-06_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-05-06_EnvContext-5.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-06-11_EnvContext-9.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-1.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-5.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-08-06_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-9.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-10.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-11.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-12.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-13.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-14.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-15.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-16.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-17.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-10-14_EnvContext-18.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-11-19_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-11-19_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-11-19_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM02_2025-11-19_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2024-11-18_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-05-07_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-05-07_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-05-07_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-05-07_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-05-07_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-7.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-06-10_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-3.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-5.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-9.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-10.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-08-05_EnvContext-11.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-2.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-9.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-10.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-11.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-12.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-13.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-14.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-15.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-16.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-17.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-18.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-19.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-20.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-21.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-22.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-23.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-24.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-25.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-26.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-10-15_EnvContext-27.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-1.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataM03_2025-11-18_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-6.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-7.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2024-11-16_EnvContext-8.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-03-20_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-03-20_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-03-20_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-03-20_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-03-20_EnvContext-5.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-05-07_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-05-07_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-05-07_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-05-07_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-05-07_EnvContext-5.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-06-10_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-06-10_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-06-10_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-06-10_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-08-07_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-10-16_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-10-16_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-10-16_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-10-16_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-11-20_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-11-20_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-11-20_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataNF01_2025-11-20_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2024-11-17_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2024-11-17_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2024-11-17_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2024-11-17_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2024-11-17_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-6.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-7.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-03-20_EnvContext-8.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-1.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-2.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-3.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-4.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-5.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-6.jpg",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-05-06_EnvContext-7.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-8.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-9.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-06-11_EnvContext-10.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-2.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-4.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-6.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-7.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-8.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-9.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-10.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-11.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-12.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-06_EnvContext-13.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-07_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-07_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-08-07_EnvContext-3.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-1.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-2.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-3.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-4.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-5.JPG",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-10-14_EnvContext-6.mp4",
                        "PRT_Sample_DataField_PhotosPRT_Sample_DataSF01_2025-11-19_EnvContext-1.JPG",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-3_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT135_ICR-1_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT135_ICR-1_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT135_ICR-1_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT001_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-2_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-2_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-2_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT002_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-2_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-2_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-2_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-3_p02.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-3_p02.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT003_ICR-3_p02.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-3_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-3_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT004_ICR-3_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-1_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-1_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-1_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-2_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-2_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-2_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-3_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-3_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT005_ICR-3_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-2_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-2_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-2_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT006_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-2_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-2_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-2_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-3_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-3_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT007_ICR-3_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-1_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-1_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-1_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-3_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-3_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT008_ICR-3_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT009_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-1_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-1_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-1_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-2_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-2_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-2_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT010_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-1_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-1_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-1_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT011_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT012_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-2_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-2_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-2_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT013_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-1_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-1_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-1_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT014_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-3_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-3_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT015_ICR-3_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT016_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-1_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-1_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-1_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-2_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-2_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-2_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT017_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT018_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-2_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-2_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-2_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT019_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-1_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-1_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-1_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT020_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT021_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-1_p2.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-1_p2.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-1_p2.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-2_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-2_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-2_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT022_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-3_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-3_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT023_ICR-3_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT025_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT026_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-1_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-1_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-1_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-3_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-3_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT027_ICR-3_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT028_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-2_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-2_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-2_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT029_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-1_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-1_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-1_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT030_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-1_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-1_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-1_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-2_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-2_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-2_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-3_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-3_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT031_ICR-3_p15.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-2_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-2_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-2_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-3_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-3_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT032_ICR-3_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-3_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-3_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT033_ICR-3_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-2_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-2_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-2_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT034_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-3_p1.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-3_p1.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT035_ICR-3_p1.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-1_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-1_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-1_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT036_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-3_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-3_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT037_ICR-3_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT038_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-1_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-1_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-1_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-2_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-2_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-2_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-3_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-3_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT044_ICR-3_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-1_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-1_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-1_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-2_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-2_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-2_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT045_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT116_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-1_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-1_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-1_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-3_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-3_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT117_ICR-3_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT119_ICR-2_p04.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT119_ICR-2_p04.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT119_ICR-2_p04.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT120_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT120_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT120_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT124_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-1_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-1_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-1_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-2_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-2_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-2_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-3_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-3_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT129_ICR-3_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-1_p2.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-1_p2.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-1_p2.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-2_p03.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-2_p03.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-2_p03.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-3_p08.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-3_p08.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT131_ICR-3_p08.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-2_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-2_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-2_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-3_p07.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-3_p07.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT132_ICR-3_p07.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-1_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-1_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-1_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-2_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-2_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-2_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-3_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-3_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT133_ICR-3_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-1_p05.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-1_p05.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-1_p05.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-2_p06.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-2_p06.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-2_p06.corems.json",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-3_p15.corems.cal",
                        "PRT_Sample_Data/FTICR/Water_CoreMS_Output_Files/PRT134_ICR-3_p15.corems.csv",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT135_ICR-1_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT001_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT001_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT002_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT002_ICR-2_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT002_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT003_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT003_ICR-2_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT003_ICR-3_p02.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT004_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT004_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT004_ICR-3_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT005_ICR-1_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT005_ICR-2_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT005_ICR-3_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT006_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT006_ICR-2_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT006_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT007_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT007_ICR-2_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT007_ICR-3_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT008_ICR-1_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT008_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT008_ICR-3_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT009_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT009_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT009_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT010_ICR-1_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT010_ICR-2_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT010_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT011_ICR-1_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT011_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT011_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT012_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT012_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT012_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT013_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT013_ICR-2_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT013_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT014_ICR-1_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT014_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT014_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT015_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT015_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT015_ICR-3_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT016_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT016_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT016_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT017_ICR-1_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT017_ICR-2_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT017_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT018_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT018_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT019_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT019_ICR-2_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT019_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT020_ICR-1_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT020_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT020_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT021_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT021_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT021_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT022_ICR-1_p2.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT022_ICR-2_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT022_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT023_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT023_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT023_ICR-3_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT025_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT025_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT025_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT026_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT026_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT026_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT027_ICR-1_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT027_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT027_ICR-3_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT028_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT028_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT028_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT029_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT029_ICR-2_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT029_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT030_ICR-1_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT030_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT030_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT031_ICR-1_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT031_ICR-2_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT031_ICR-3_p15.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT032_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT032_ICR-2_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT032_ICR-3_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT033_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT033_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT033_ICR-3_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT034_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT034_ICR-2_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT034_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT035_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT035_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT035_ICR-3_p1.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT036_ICR-1_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT036_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT036_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT037_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT037_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT037_ICR-3_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT038_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT038_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT038_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT044_ICR-1_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT044_ICR-2_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT044_ICR-3_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT045_ICR-1_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT045_ICR-2_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT045_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT116_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT116_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT117_ICR-1_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT117_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT117_ICR-3_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT119_ICR-2_p04.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT120_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT124_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT124_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT124_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT129_ICR-1_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT129_ICR-2_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT129_ICR-3_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT131_ICR-1_p2.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT131_ICR-2_p03.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT131_ICR-3_p08.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT132_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT132_ICR-2_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT132_ICR-3_p07.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT133_ICR-1_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT133_ICR-2_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT133_ICR-3_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT134_ICR-1_p05.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT134_ICR-2_p06.xml",
                        "PRT_Sample_Data/FTICR/Water_XML_Files/PRT134_ICR-3_p15.xml")

# include_files = vector of files (relative file path + file name) to include from within the dir. Optional argument; default is NA_character_. 
user_include_files = NA_character_

# include_dot_files = T/F to indicate whether you want to include hidden files that begin with "." (usually github related files). Optional argument; default is FALSE.
user_include_dot_files = F

# add_placeholders = T/F where the user should select T if they want placeholder rows for the flmd, readme, and dd if those files are missing. Optional argument; default is FALSE.
user_add_placeholders = T

# query_header_info = T/F where the user should select T if header rows are present and F if all tabular files do NOT have header rows. Header rows that start with "#" can be considered as not having header rows. Optional argument; default is FALSE.  
user_query_header_info = T

# file_n_max = number of rows to load in. The only time you'd want to change this is if there are more than 20 rows before the data matrix starts; if that is the case, then increase this number. Optional argument; default is 20. 
user_view_n_max = 20

# add_boye_headers = T/F where the user should select T if they want placeholder rows in the dd for Boye header row names. Optional argument; default is FALSE.
user_add_boye_headers = T

# add_flmd_dd_headers = T/F where the user should select T if they want placeholder rows for FLMD and DD column headers. Optional argument; default is FALSE. 
user_add_flmd_dd_headers = T

# include_filenames = T/F to indicate whether you want to include the file name(s) the headers came from. Optional argument; default is F. 
user_include_filenames = F

# dd_database_path = absolute path to the dd database 
# user_dd_database_path <- "C:/Brieanne/GitHub/rcsfa-data_processing_for_publication/Data_Package_Documentation/database/data_dictionary_database.csv"
user_dd_database_path <- "C:/Users/forb086/Documents/GitHub/rcsfa-data_processing_for_publication/Data_Package_Documentation/database/data_dictionary_database.csv"

# flmd_database_path = absolute path to the flmd database 
# user_flmd_database_path <- "C:/Brieanne/GitHub/rcsfa-data_processing_for_publication/Data_Package_Documentation/database/file_level_metadata_database.csv"
user_flmd_database_path <- "C:/Users/forb086/Documents/GitHub/rcsfa-data_processing_for_publication/Data_Package_Documentation/database/file_level_metadata_database.csv"

### Prep Script ################################################################

# load libraries
library(tidyverse)
library(rlog)
library(fs)
library(devtools)
library(crayon)

# source functions
source_url("https://raw.githubusercontent.com/river-corridors-sfa/rcsfa-data_processing_for_publication/refs/heads/main/Data_Package_Documentation/functions/create_flmd.R")
source_url("https://raw.githubusercontent.com/river-corridors-sfa/rcsfa-data_processing_for_publication/refs/heads/main/Data_Package_Documentation/functions/create_dd.R")
source_url("https://github.com/river-corridors-sfa/rcsfa-data_processing_for_publication/raw/refs/heads/main/Data_Package_Documentation/functions/query_dd_database.R")
source_url("https://github.com/river-corridors-sfa/rcsfa-data_processing_for_publication/raw/refs/heads/main/Data_Package_Documentation/functions/query_flmd_database.R")

### Get Files ##################################################################

my_files <- get_files(directory = my_directory, 
                      exclude_files = user_exclude_files, 
                      include_files = user_include_files, 
                      include_dot_files = user_include_dot_files)

### Create FLMD ################################################################

my_flmd<- create_flmd(files_df = my_files,
                       dp_keyword = my_dp_keyword,
                       add_placeholders = user_add_placeholders,
                       query_header_info = user_query_header_info,
                       view_n_max = user_view_n_max)


### Create DD ##################################################################

my_dd <- create_dd(files_df = my_files, 
                    flmd_df = my_flmd, 
                    add_boye_headers = user_add_boye_headers, 
                    add_flmd_dd_headers = user_add_flmd_dd_headers, 
                    include_filenames = user_include_filenames)


### Populate dd/flmd from database #############################################

if(populate_dd_flmd == T){

  
dd_populated <-  query_dd_database(dd_database_abs_path = user_dd_database_path,
                                   dd_skeleton = my_dd)

flmd_populated <- query_flmd_database(flmd_database_abs_path = user_flmd_database_path,
                                    flmd_skeleton = my_flmd)


### Data Package Specific Edits ################################################

# prelim_dd <- read_csv("Z:/00_ESSDIVE/01_Study_DPs/ECA_Data_Package_v2/EC_dd.csv") %>%
#   select(Column_or_Row_Name, Unit, Definition, Data_Type, Term_Type)
# 
# 
# dd_populated <- my_dd %>%
#   rows_patch(prelim_dd, by = c("Column_or_Row_Name"), unmatched = 'ignore') %>%
#   mutate(Term_Type = case_when(is.na(Term_Type) ~ "column_header",
#                                T ~ Term_Type))
# 
# prelim_flmd <- read_csv("Z:/00_ESSDIVE/01_Study_DPs/ECA_Data_Package_v2/EC_flmd.csv") %>%
#   select(File_Name, File_Description)
# 
# 
# flmd_populated <- my_flmd %>%
#   rows_patch(prelim_flmd, by = c("File_Name"), unmatched = 'ignore')


### Export #####################################################################

write_csv(flmd_populated, file = paste0(my_out_dir, "/", my_dp_keyword, "_flmd.csv"), na = "")

write_csv(dd_populated, file = paste0(my_out_dir, "/", my_dp_keyword, "_dd.csv"), na = "")

} else{

write_csv(my_flmd, file = paste0(my_out_dir, "/", my_dp_keyword, "_flmd.csv"), na = "")

write_csv(my_dd, file = paste0(my_out_dir, "/", my_dp_keyword, "_dd.csv"), na = "")

}

