### data_package_create_flmd_dd.R ##############################################

# Objective: 
  # Run this script to generate dd and flmds.
  # It will create empty data dictionary and file-level metadata skeletons.
  # Then it will begin to fill in those skeletons by querying the database. 


### User Inputs ################################################################
# Directions: Fill out the user inputs. Then run the chunk.

# data package directory (do not include a "/" at the end)
directory <- "C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages/EWEB V2"

# directory where you want the dd and flmd to be written out to (do not include a "/" at the end)
out_directory <- "C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages/EWEB V2"
  

### Prep Script ################################################################
# Directions: Run this chunk without modification.

# load libraries
library(rstudioapi)
library(tidyverse)
library(rlog)
library(fs)
library(clipr)
library(tools)

# set working directory to this GitHub repo (rcsfa-data-processing-for-publication)
current_path <- rstudioapi::getActiveDocumentContext()$path # get current path
setwd(dirname(current_path)) # set wd to current path
rm(current_path)
setwd("../...") # move wd back to the repo directory
getwd()
original_wd <- getwd()

# load functions
source("./Data_Transformation/functions/load_tabular_data.R")
source("./Data_Package_Documentation/functions/create_dd_skeleton.R")
source("./Data_Package_Documentation/functions/create_flmd_skeleton.R")
source("./Data_Package_Documentation/functions/query_dd_database.R")
source("./Data_Package_Documentation/functions/query_flmd_database.R")


# load helper functions
source("./Data_Transformation/functions/rename_column_headers.R")


### Run Functions ##############################################################
# Directions: Run chunk without modification. Answer inline prompts as they appear. 


# 1. Load data
# for excluding or including files, write the relative path from the directory, without slash in the beginning
data_package_data <- load_tabular_data(directory, exclude_files = c("FTICR_Data/EWEB_Nov2020_E040_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E040_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_05-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_05-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_06-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_06-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_20-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_20-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_21-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_22-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_22-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_23-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_23-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E390_24-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_05-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_05-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_06-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_06-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_20-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_20-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_21-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_21-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_22-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_22-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_23-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_23-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_24-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E410_24-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_05-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_05-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_15-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_20-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_20-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_21-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_21-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_22-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_22-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_24-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E430_24-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E431_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_05-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_05-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_06-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_06-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_15-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_21-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_21-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_22-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_22-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_23-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_23-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_24-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E440_24-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_02-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_02-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_03-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_03-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_04-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_04-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_05-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_05-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_06-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_06-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_15-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_20-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_20-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_21-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_21-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_22-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_22-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_23-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_23-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_24-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_E547_24-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_MethodB3-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2020_MethodB3-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E020_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E020_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E040_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E040_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E310_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E360_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E360_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E390_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E410_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_15-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E430_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E431_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E431_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E432_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E432_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_06-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_06-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_07-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_07-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_08-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_08-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_09-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_09-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_10-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_10-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_11-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_11-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_12-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_12-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_13-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_13-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_14-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_14-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_15-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_15-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_16-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_16-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_17-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_17-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_18-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_18-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_19-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E440_19-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E543_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E543_01-r2_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E547_01-r1_p5.xml",
                                                                    "FTICR_Data/EWEB_Nov2021_E547_01-r2_p5.xml",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E390_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E390_13_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E390_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E410_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E410_06_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E410_11_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E410_15_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E430_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E430_08_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E430_12_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E430_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E440_04_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E440_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E440_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E440_21_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E547_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E547_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E547_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Apr2022_E547_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E020_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E040_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E310_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E360_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_06_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_08_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_09_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_11_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_12_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_13_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_14_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_15_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_17_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E390_19_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_08_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_09_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_11_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_12_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_13_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_14_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_15_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_17_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E410_19_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_06_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_08_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_09_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_11_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_12_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_13_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_14_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_15_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_17_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E430_19_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E431_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E432_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_06_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_07_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_08_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_09_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_10_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_11_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_12_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_13_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_14_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_15_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_16_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_17_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_18_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E440_19_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E543_01_DilCorr_Abs.csv",
                                                                    "EEMs/Absorbance/EWEB_Nov2021_E547_01_DilCorr_Abs.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E390_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E390_13_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E390_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E410_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E410_06_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E410_11_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E410_15_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E430_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E430_08_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E430_12_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E430_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E440_04_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E440_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E440_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E440_21_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E547_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E547_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E547_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Apr2022_E547_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E020_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E040_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E310_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E360_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_06_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_08_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_09_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_11_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_12_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_13_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_14_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_15_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_17_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E390_19_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_08_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_09_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_11_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_12_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_13_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_14_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_15_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_17_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E410_19_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_06_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_08_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_09_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_11_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_12_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_13_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_14_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_15_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_17_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E430_19_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E431_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E432_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_06_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_07_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_08_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_09_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_10_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_11_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_12_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_13_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_14_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_15_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_16_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_17_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_18_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E440_19_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E543_01_DilCorr_IFE_RamNorm.csv",
                                                                    "EEMs/Fluorescence/EWEB_Nov2021_E547_01_DilCorr_IFE_RamNorm.csv"))

# 2a. create dd skeleton
dd_skeleton <- create_dd_skeleton(data_package_data$headers)


# 2b. populate dd
# dd_skeleton_populated <- query_dd_database(dd_skeleton)


# 3a. create flmd skeleton
flmd_skeleton <- create_flmd_skeleton(data_package_data$file_paths_relative)


# 3b. populate flmd
# flmd_skeleton_populated <- query_flmd_database(flmd_skeleton)

### DP Specific Edits ##########################################################

# left join prelim dd to this dd

prelim_dd <- read_csv("C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages/Archive/v2_EWEB_dd.csv")

dd_skeleton <- dd_skeleton %>%
  select(Column_or_Row_Name) %>%
  left_join(prelim_dd, by = c("Column_or_Row_Name")) %>%
  add_row( prelim_dd%>%
             filter(!str_detect(Column_or_Row_Name, 'CA_uM')) %>%
             anti_join(dd_skeleton, by = c("Column_or_Row_Name")) ) %>%
  arrange(Column_or_Row_Name) 



# left join prelim flmd to this flmd

prelim_flmd <- read_csv("C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages/Archive/v2_EWEB_flmd.csv")%>%
  select(-File_Path)

flmd_skeleton <- flmd_skeleton %>%
  select(File_Name, File_Path) %>%
  left_join(prelim_flmd, by = c("File_Name")) %>%
  select(-File_Path, File_Path)


### Export #####################################################################
# Directions: 
  # Export out .csvs at your choosing. Only run the lines you want. 
  # After exporting, remember to properly rename the dd and flmd files and to update the flmd to reflect such changes.

# write out data package data
save(data_package_data, file = paste0(out_directory, "/data_package_data.rda"))

# write out skeleton dd
write_csv(dd_skeleton, paste0(out_directory, "/skeleton_dd.csv"), na = "")

# write out populated dd
# write_csv(dd_skeleton_populated, paste0(out_directory, "/skeleton_populated_dd.csv"), na = "")

# write out skeleton flmd
write_csv(flmd_skeleton, paste0(out_directory, "/skeleton_flmd.csv"), na = "")

# writ eout populated flmd
# write_csv(flmd_skeleton_populated, paste0(out_directory, "/skeleton_populated_flmd.csv"), na = "")

# open the directory the files were saved to
shell.exec(out_directory)


