### data_package_checks.R ######################################################

# Objective: Use this script to run data package checks.

# This script walks you through the steps to read in the data and run it through
# the checks. It relies on `checks.R`, which is the script that houses the
# functions that validate the data and produce tabular outputs. Those tabular
# outputs are then read into the `checks_report.Rmd` file to create the graphics
# and visual report.

# See README_data_package_checks.md for more details on how to run or update the
# checks.

rm(list=ls(all=T))

### User Inputs ################################################################
# Directions: Fill out the user inputs. Then run the chunk.

# data package directory (provide absolute directory; do not include a "/" at the end)
directory <- "C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages/EWEB V2"

# provide the name of the person running the checks
report_author <- "Brieanne Forbes"

# provide the directory (do not include "/" at the end) for the data package report - the report will be saved as Checks_Report_YYYY-MM-DD.html
report_out_dir <- "C:/Brieanne/GitHub/rcsfa-RC3-EWEB-BPCAs/data-packages"

# do the tabular files have header rows? (T/F)
user_input_has_header_rows <- T

# do you already have an FLMD that has Header_Rows and Column_or_Row_Name_Position filled out? (T/F)
has_flmd <- F

# if T, then provide the absolute file path of the existing flmd file
flmd_path <- ""


### Prep Script ################################################################
# Directions: Run this chunk without modification.

library(here) # for setting wd at git repo
library(tidyverse)
library(rlog)
library(devtools) # for sourcing from github
library(hms) # for handling times
library(fs) # for tree diagram
library(clipr) # for copying to clipboard
library(knitr) # for kable
library(kableExtra) # for rmd report table styling
library(DT) # for interactive tables in report
library(rmarkdown) # for rendering report
library(plotly) # for interactive graphs
library(downloadthis) # for downloading tabular data report as .csv



# set working dir
current_path <- rstudioapi::getActiveDocumentContext()$path
setwd(dirname(current_path))
setwd("./..")

# load functions
source_url("https://raw.githubusercontent.com/river-corridors-sfa/rcsfa-data_processing_for_publication/database_v2/Data_Transformation/functions/load_tabular_data_from_flmd.R") # note: will need to update this link after I merge branches
source_url("https://raw.githubusercontent.com/river-corridors-sfa/rcsfa-data_processing_for_publication/data_checks_v2/Data_Package_Validation/functions/checks.R") # note: will need to update this link after I merge branches

### Run Functions ##############################################################
# Directions: Run this chunk without modification. Answer inline prompts as they appear.

# confirm directory has files in it
if (length(list.files(directory, recursive = T)) == 0) {
  warning("Your directory has 0 files.")
}

# 1. Load flmd if applicable
if (has_flmd == T) {
  data_package_flmd <- read_csv(flmd_path) %>% 
  # convert to R's NA
  mutate(across(everything(), ~ case_when(. == -9999 ~ NA, 
                                          . == "N/A" ~ NA,
                                          TRUE ~ .)))
} else if (has_flmd == F) {
  data_package_flmd <- NA 
  }


# 2. Load data
data_package_data <- load_tabular_data_from_flmd(directory = directory, flmd_df = data_package_flmd, query_header_info = user_input_has_header_rows,
                                                 exclude_files = c("FTICR_Data/EWEB_Nov2020_E040_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E040_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_05-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_05-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_06-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_06-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_20-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_20-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_21-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_22-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_22-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_23-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_23-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E390_24-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_05-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_05-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_06-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_06-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_20-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_20-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_21-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_21-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_22-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_22-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_23-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_23-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_24-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E410_24-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_05-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_05-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_15-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_20-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_20-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_21-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_21-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_22-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_22-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_24-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E430_24-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E431_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_05-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_05-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_06-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_06-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_15-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_21-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_21-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_22-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_22-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_23-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_23-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_24-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E440_24-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_02-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_02-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_03-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_03-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_04-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_04-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_05-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_05-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_06-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_06-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_15-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_20-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_20-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_21-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_21-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_22-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_22-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_23-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_23-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_24-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_E547_24-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_MethodB3-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2020_MethodB3-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E020_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E020_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E040_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E040_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E310_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E360_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E360_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E390_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E410_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_15-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E430_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E431_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E431_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E432_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E432_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_06-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_06-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_07-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_07-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_08-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_08-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_09-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_09-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_10-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_10-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_11-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_11-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_12-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_12-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_13-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_13-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_14-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_14-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_15-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_15-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_16-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_16-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_17-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_17-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_18-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_18-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_19-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E440_19-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E543_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E543_01-r2_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E547_01-r1_p5.xml",
                                                                     "FTICR_Data/EWEB_Nov2021_E547_01-r2_p5.xml",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E390_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E390_13_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E390_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E410_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E410_06_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E410_11_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E410_15_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E430_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E430_08_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E430_12_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E430_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E440_04_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E440_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E440_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E440_21_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E547_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E547_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E547_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Apr2022_E547_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E020_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E040_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E310_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E360_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_06_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_08_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_09_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_11_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_12_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_13_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_14_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_15_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_17_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E390_19_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_08_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_09_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_11_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_12_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_13_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_14_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_15_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_17_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E410_19_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_06_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_08_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_09_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_11_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_12_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_13_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_14_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_15_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_17_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E430_19_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E431_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E432_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_06_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_07_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_08_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_09_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_10_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_11_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_12_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_13_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_14_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_15_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_16_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_17_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_18_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E440_19_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E543_01_DilCorr_Abs.csv",
                                                                     "EEMs/Absorbance/EWEB_Nov2021_E547_01_DilCorr_Abs.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E390_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E390_13_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E390_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E410_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E410_06_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E410_11_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E410_15_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E430_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E430_08_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E430_12_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E430_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E440_04_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E440_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E440_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E440_21_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E547_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E547_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E547_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Apr2022_E547_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E020_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E040_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E310_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E360_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_06_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_08_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_09_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_11_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_12_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_13_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_14_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_15_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_17_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E390_19_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_08_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_09_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_11_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_12_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_13_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_14_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_15_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_17_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E410_19_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_06_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_08_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_09_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_11_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_12_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_13_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_14_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_15_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_17_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E430_19_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E431_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E432_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_06_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_07_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_08_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_09_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_10_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_11_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_12_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_13_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_14_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_15_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_16_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_17_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_18_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E440_19_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E543_01_DilCorr_IFE_RamNorm.csv",
                                                                     "EEMs/Fluorescence/EWEB_Nov2021_E547_01_DilCorr_IFE_RamNorm.csv"))

# preview data - this shows all the tabular data you loaded in so you can quickly check if it loaded in correctly without having to poke around in the nested lists
invisible(lapply(names(data_package_data$tabular_data), function(name) {
  cat("\n--- Data Preview of", name, "---\n")
  glimpse(data_package_data$tabular_data[[name]])
}))


# 3. Run checks
data_package_checks <- check_data_package(data_package_data = data_package_data, input_parameters = input_parameters)


# 4. Generate report
out_file <- paste0("Checks_Report_", Sys.Date(), ".html")
render("./Data_Package_Validation/functions/checks_report.Rmd", output_format = "html_document", output_dir = report_out_dir, output_file = out_file)
browseURL(paste0(report_out_dir, "/", out_file))

